### GET request with a header
GET http://localhost:8080
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/x-www-form-urlencoded

_csrf = ikrObaLUklv07gSNOqgXO83jt6SP9YJqfgON-PcrD6Hc1dFi6372CZvn82LZiGC5DoUjWvSCmpy6zeBHR2K_z88TapPk7bQB

### Send GET request with json body
GET http://localhost:8080/csrfToken
Content-Type: application/json